language: cpp
sudo: false
addons:
    apt:
        packages:
            - libopenal-dev
            - libogg-dev
            - libvorbis-dev
            - build-essential
            - automake
            - autoconf
            - libsdl1.2-dev
            - libtheora-dev
            - libreadline6-dev
            - libpng12-dev
            - libjpeg62-dev
            - liblua5.1-0-dev
            - libjansson-dev
            - libtool

    coverity_scan:
        project:
            name: scp-fs2open/fs2open.github.com
            description: Coverity via Travis CI
        notification_email: niffiwan.scp@gmail.com
        build_command_prepend: "./autogen.sh --enable-debug"
        build_command: make -j2
        branch_pattern: coverity_scan

deploy:
    - provider: releases
      api_key:
          secure: "bBWEBF+r4p7kea+Lj/vHD0CCW4AsxqlLri8gT3HbsdPuKwdSNU4QLLFk9yAXmmBF2T/fe45Zk+WQrdQJjSydkpG06M7sFD22RKOYv3cLF0Bq0nEG4CpuXoGqo77oFGkA5hdU6D8W2nQTMhPuiqlvhgt3zeD/6fiyfdAztbtKNRs="
      skip_cleanup: true 
      file_glob: true
      file: "/tmp/builds/*.tar.gz"
      on:
          condition: '"$RELEASE_BUILD" == true'
          tags: true
        
    - provider: bintray
      user: asarium
      api_key:
          secure: "JyJIsJFxCvNjmdyG9eDIvkzXFqsJQVzXKp5BeJcn5WSdMA2Vs7dCvarJXomdwe3F3RCrdmrFYCaimiCDD6LqImrcDLzxlevzGlNUv381iFna612SJj672d8iQCgtMibIJ3HzYmgZlsaJ9YcaOuccRyQIV/TNUcwgzbsW27CPEcM="
      dry-run: true
      on:
          condition: '"$NIGHTLY_BUILD" == true'

env:
    global:
    - secure: C3wF967ZeliwwP1vC12EMIBOaC568n26Z/cPnwzn317ve59DWH3YSfPZVgvt08GzmaXITGGsJvPB+qxfGoKvQzYE4O1B73q81RpUe5pB3IhF+ThQ91VfQZIRJR5xEGJaLINUlHTTZGX5jxlkVO9wAcauVj/s3b8sQ3dvUZauPvk=
matrix:
    include:
        - os: linux
          compiler: gcc
          env: CONFIGURATION="Debug"
        - os: linux
          compiler: clang
          env: CONFIGURATION="Debug"
        - os: osx
          compiler: clang
          env: CONFIGURATION="Debug" MACOSX_ARCH=i386
        - os: osx
          compiler: clang
          env: CONFIGURATION="Debug" MACOSX_ARCH=x86_64
        - os: linux
          compiler: gcc
          env: CONFIGURATION="Release"
        - os: linux
          compiler: clang
          env: CONFIGURATION="Release"
        - os: osx
          compiler: clang
          env: CONFIGURATION="Release" MACOSX_ARCH=i386
        - os: osx
          compiler: clang
          env: CONFIGURATION="Release" MACOSX_ARCH=x86_64

before_install:
    - if ([[ "${TRAVIS_JOB_NUMBER##*.}" != "1" ]] && [[ "${TRAVIS_BRANCH}" == "coverity_scan" ]]); then false ; fi
    - source "./ci/travis/check_release.sh"
    - "./ci/travis/before_install.sh"
install:
    - "./ci/travis/install.sh"
before_script:
    - "./ci/travis/before_script.sh"
script:
    - if [ "$BUILD_DEPLOYMENT" = true ] ; then ./ci/travis/release.sh ; else ./ci/travis/script.sh ; fi
