version: 3.7.3.{build}
shallow_clone: true
environment:
  matrix:
  - VisualStudioVersion: 10.0
    PlatformToolset: v100
    ProjectPath: projects/MSVC_2010/Freespace2.vcxproj
    ReleaseConfig: False
  - VisualStudioVersion: 12.0
    PlatformToolset: v120
    ProjectPath: projects/MSVC_2013/Freespace2.vcxproj
    ReleaseConfig: False
  - VisualStudioVersion: 14.0
    PlatformToolset: v140
    ProjectPath: projects/MSVC_2015/Freespace2.vcxproj
    ReleaseConfig: True
build_script:
    - ps: . ./ci/appveyor/check_release.ps1
    - ps: . ./ci/appveyor/build.ps1
test: off
