version: 3.7.3.{build}
branches:
  only:
    - cmake
configuration:
  - Debug
  - Release
platform: x86
shallow_clone: true
environment:
  matrix:
    - VS_VERSION: 10
    - VS_VERSION: 14
init:
  - CALL "C:\Program Files (x86)\Microsoft Visual Studio %VS_VERSION%.0\VC\vcvarsall.bat" x86
install:
  - cinst ninja -y
  - SET PATH=%PATH%;C:\tools\ninja
before_build:
  - ps: . $Env:APPVEYOR_BUILD_FOLDER/ci/appveyor/before_build.ps1
build_script:
  - ps: . $Env:APPVEYOR_BUILD_FOLDER/ci/appveyor/build.ps1
