version: 3.7.3.{build}
branches:
  only:
    - cmake
configuration:
  - Debug
  - Release
shallow_clone: true
environment:
  matrix:
    - VS_VERSION: 10
      CMAKE_GENERATOR: Visual Studio 10 2010
    - VS_VERSION: 14
      CMAKE_GENERATOR: Visual Studio 14 2015
before_build:
  - ps: . $Env:APPVEYOR_BUILD_FOLDER/ci/appveyor/before_build.ps1
build_script:
  - ps: . $Env:APPVEYOR_BUILD_FOLDER/ci/appveyor/build.ps1
