version: 3.7.3.{build}
branches:
  only:
    - build/ci
configuration:
  - Debug
  - Release
platform: x86
shallow_clone: true
environment:
  matrix:
    - INSTRUCTION_SET: SSE2
    - INSTRUCTION_SET: AVX
init:
  - CALL "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86
install:
  - cinst ninja -y
  - SET PATH=%PATH%;C:\tools\ninja
  - cinst wget -y
  - wget -nv -O nsis-installer.exe http://prdownloads.sourceforge.net/nsis/nsis-2.46-setup.exe?download
  - nsis-installer.exe /S
before_build:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%\install" -DCMAKE_BUILD_TYPE="%CONFIGURATION%" -DFSO_INSTRUCTION_SET="%INSTRUCTION_SET%" -G "Ninja" ..
build_script:
  - cmake --build .
after_build:
  - cmake --build . --target install
artifacts:
  - path: $(APPVEYOR_BUILD_FOLDER)\install\**\*.*
    name: binaries
