version: 1.0.0.{build}
configuration:
  - Debug
  - Release
shallow_clone: true
environment:
  matrix:
    #- VS_VERSION: 10
    #  CMAKE_GENERATOR: Visual Studio 10 2010
    #  PlatformToolset: v100
    - VS_VERSION: 14
      CMAKE_GENERATOR: Visual Studio 14 2015
      PlatformToolset: v140_xp
before_build:
  - ps: . $Env:APPVEYOR_BUILD_FOLDER/ci/appveyor/before_build.ps1
build_script:
  - ps: . $Env:APPVEYOR_BUILD_FOLDER/ci/appveyor/build.ps1


deploy:
    - provider: GitHub
      auth_token:
          secure: RWe6hwCcgBdklaYvjB62kzhKn7yDBJdqoDDKYViShaEV9HkJ75HbawsBcGBimRUu
      on:
          ReleaseBuild: true        # deploy on release push only

    - provider: BinTray
      username: asarium
      api_key:
          secure: 2lHma1ZreuB4CCE5hSdp+gqFjCMzUDj3tVJhP+D6EyF5wIVMLlwXFrISwnYu1kJi
      subject: asarium
      repo: FSO
      package: nightly
      version: $(VersionName)
      publish: true
      override: true
      on:
          NightlyBuild: true        # deploy on nightly push only