version: 3.7.3.{build}
shallow_clone: true
environment:
  matrix:
  - VisualStudioVersion: 10.0
    PlatformToolset: v100
    ProjectPath: projects/MSVC_2010
    DeployConfig: False
  - VisualStudioVersion: 12.0
    PlatformToolset: v120
    ProjectPath: projects/MSVC_2013
    DeployConfig: False
  - VisualStudioVersion: 14.0
    PlatformToolset: v140
    ProjectPath: projects/MSVC_2015
    DeployConfig: True
build_script:
    - ps: . ./ci/appveyor/check_release.ps1
    - ps: . ./ci/appveyor/build.ps1
test: off
deploy:
    - provider: GitHub
      auth_token:
          secure: RWe6hwCcgBdklaYvjB62kzhKn7yDBJdqoDDKYViShaEV9HkJ75HbawsBcGBimRUu
      on:
          ReleaseBuild: true        # deploy on release push only

    - provider: BinTray
      username: asarium
      api_key:
          secure: 2lHma1ZreuB4CCE5hSdp+gqFjCMzUDj3tVJhP+D6EyF5wIVMLlwXFrISwnYu1kJi
      subject: asarium
      repo: FSO
      package: nightly
      version: $(APPVEYOR_REPO_COMMIT)
      publish: true
      override: true
      on:
          NightlyBuild: true        # deploy on nightly push only