version: 3.7.3.{build}
branches:
  only:
    - build/ci
configuration:
  - Debug
  - Release
platform: x86
shallow_clone: true
environment:
  INSTALL_DIR: c:\projects\install
init:
  - CALL "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86
install:
  - cinst ninja -y
  - SET PATH=%PATH%;C:\tools\ninja
  - cinst wget -y
  - wget -nv -O nsis-installer.exe http://prdownloads.sourceforge.net/nsis/nsis-2.46-setup.exe?download
  - nsis-installer.exe /S
before_build:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX="%INSTALL_DIR%" -DCMAKE_BUILD_TYPE="%CONFIGURATION%" -G "Ninja" ..
  - dir
build_script:
  - dir
  - cmake --build .
after_build:
  - dir
  - cmake --build . --target install
artifacts:
  path: '%INSTALL_DIR%'
  name: install
